Repository lo1tuma/pr-log, pull requests merged in 2023-09, with the labels that each got.

#298 Rewrite codebase to TypeScript (drop nodejs support for versions < 20)
  .babelrc
  .c8rc.json
  .eslintignore
  .eslintrc.json
  .github/workflows/ci.yml
  .gitignore
  .prettierignore
  LICENSE
  ava.config.js
  bin/pr-log.js
  lib/cli.js
  lib/createChangelog.js
  lib/ensureCleanLocalGitState.js
  lib/getMergedPullRequests.js
  lib/getPullRequestLabel.js
  package-lock.json
  package.json
  prettier.config.js
  source/bin/pr-log.ts
  source/lib/cli.test.ts
  source/lib/cli.ts
  source/lib/create-changelog.test.ts
  source/lib/create-changelog.ts
  source/lib/ensure-clean-local-git-state.test.ts
  source/lib/ensure-clean-local-git-state.ts
  source/lib/find-remote-alias.test.ts
  source/lib/find-remote-alias.ts
  source/lib/get-github-repo.test.ts
  source/lib/get-github-repo.ts
  source/lib/get-merged-pull-requests.test.ts
  source/lib/get-merged-pull-requests.ts
  source/lib/get-pull-request-label.test.ts
  source/lib/get-pull-request-label.ts
  source/lib/valid-labels.ts
  source/tsconfig.json
  source/tsconfig.sources.json
  source/tsconfig.unit-tests.json
  test/unit/lib/getMergedPullRequestsSpec.js
  tsconfig.base.json
  tsconfig.json
Labels: breaking

#300 Refactoring: introduce GitCommandRunner
  .c8rc.json
  source/bin/pr-log.ts
  source/lib/cli.test.ts
  source/lib/ensure-clean-local-git-state.test.ts
  source/lib/ensure-clean-local-git-state.ts
  source/lib/find-remote-alias.test.ts
  source/lib/find-remote-alias.ts
  source/lib/get-merged-pull-requests.test.ts
  source/lib/get-merged-pull-requests.ts
  source/lib/get-pull-request-label.test.ts
  source/lib/get-pull-request-label.ts
  source/lib/git-command-runner.test.ts
  source/lib/git-command-runner.ts
  source/lib/split.test.ts
  source/lib/split.ts
  source/tsconfig.sources.json
Labels: refactor

#305 Remove quotes from git log format
  source/lib/git-command-runner.test.ts
  source/lib/git-command-runner.ts
Labels: bug

#306 Fix token authentication
  source/bin/pr-log.ts
Labels: bug

#307 Fix parsing of git commit log messages
  source/lib/git-command-runner.test.ts
  source/lib/git-command-runner.ts
Labels: bug

#308 Ensure there is always an empty line between the existing content and the new content in CHANGELOG.md
  source/lib/cli.test.ts
  source/lib/cli.ts
Labels: bug

#310 Specify versions of GitHub actions
  .github/workflows/ci.yml
Labels: build

#309 Force exact dependency installation
  .npmrc
  package-lock.json
  package.json
Labels: refactor
